# Generated by Django 4.2.5 on 2023-10-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_name', models.CharField(max_length=100)),
            ],
        ),
    ]
